routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// users dashboard route
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/status', 'UserStatusController');

// doctors dashboard route
Route::get('/config_cache', function() {
    $exitCode = Artisan::call('config:cache');
    return 'config cache cleared' . $exitCode;
})->middleware('isAdmin');

Route::get('/migrate', function() {
    $exitCode = Artisan::call('migrate');
    return 'migration done' . $exitCode;
})->middleware('isAdmin');

Route::get('/admin', 'AdminController@index')->name('admin')->middleware('isAdmin');

Route::resource('/admin/user', 'AdminUserController');
Route::resource('/admin/tmc', 'TelemedicineController')->middleware('isAdmin');
Route::post('/admin/user/search', 'AdminUserController@search')->middleware('isAdmin')->name('search');

Route::get('/admin/stat', 'StatisticController@index')->middleware('isAdmin')->name('stat');
Route::post('/admin/stat', 'StatisticController@getStat')->middleware('isAdmin')->name('stat.data');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
    'last_name',
    'name',
    'second_name',
    'birth_day',
    'email',
    'phone_number',
    'arrival_date',
    'current_address',
    'hospital_number',
    'arrival_country',
    'quarantine_end_date',
    'take_1',
    'take_1_result',
    'take_2',
    'take_2_result',
    'take_3',
    'take_3_result',
    'take_1_comment',
    'take_2_comment',
    'take_3_comment',
    'is_need_bl',
    'bl_receive_date',
    'child_qty',
    'job',
    'control_end_date',
    'control_result',
    'isolation_conditions',
    'ext_information',
    'role',
    'email_verified_at',
    'password'
    ];
    

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function user_statuses()
    {
        return $this->hasMany('App\User_status');
    }

    public function telemedicines()
    {
        return $this->hasMany('App\Telemedicine');
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.app')
@section('content')
<h1>Новый пользователь(создать)</h1>
@if (isset($error_message))
<div class="alert alert-danger" role="alert">
    {{  $error_message }}
</div>
@endif
{{ Form::open(array('route' => "user.store")) }}
<div class="row">
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('last_name', 'Фамилия (Обязательное поле)') }}
            {{ Form::text('last_name', $last_name ?? null, ['class'=>"form-control", 'placeholder'=>"Фамилия", 'required'=>'']) }}
        </div>
    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('name', 'Имя (Обязательное поле)') }}
            {{ Form::text('name', $name ?? null, ['class'=>"form-control", 'placeholder'=>"Имя", 'required'=>'']) }}
        </div>
    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('second_name', 'Отчество') }}
            {{ Form::text('second_name', $second_name ?? null, ['class'=>"form-control", 'placeholder'=>"Отчество"]) }}
        </div>
    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('hospital_number', 'Номер отделения') }}
            {{ Form::number('hospital_number', $hospital_number ?? null, ['class'=>"form-control"]) }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm " style='max-width:240px;'>
        <div class="form-group">
            {{ Form::label('birth_day', 'Дата рождения') }}
            {{ Form::date('birth_day', $birth_day ?? null, ['class'=>"form-control"]) }}
        </div>
    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('phone_number', 'Телефон') }}
            {{ Form::text('phone_number', $phone_number ?? null, ['class'=>"form-control", 'placeholder'=>"Телефон"]) }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('current_address', 'Текущий Адрес') }}
            {{ Form::text('current_address', $current_address ?? null, ['class'=>"form-control", 'placeholder'=>"Введите адрес"]) }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('child_qty', 'Количество детей') }}
            {{ Form::number('child_qty', $child_qty ?? null, ['class'=>"form-control"]) }}
        </div>
    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('job', 'Место работы') }}
            {{ Form::text('job', $job ?? null, ['class'=>"form-control", 'placeholder'=>"Наименование предприятия"]) }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('arrival_date', 'Дата прибытия') }}
            {{ Form::date('arrival_date', $arrival_date ?? null, ['class'=>"form-control", "id"=>"arrival_date"]) }}
        </div>
    </div>
    <div class="col-sm-1 pt-4">
        <button type="button" class="btn btn-primary btn-sm mb-1" id="addTwoWeeks">+ 14 дней</a>
    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('quarantine_end_date', 'Дата окончания карантина',['id'=>"dateDelta"]) }}
            {{ Form::date('quarantine_end_date', $quarantine_end_date ?? null, ['class'=>"form-control", 'id'=>"quarantine_end_date"]) }}
        </div>
    </div>

    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('arrival_country', 'Страна прибытия / контакт') }}
            {{ Form::text('arrival_country', $arrival_country ?? null, ['class'=>"form-control", 'placeholder'=>"arrival_country"]) }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('is_need_bl', 'Нужен больничный?') }}
            {{ Form::select('is_need_bl', ['0' => 'Нет', '1' => 'Да'], $is_need_bl ?? '0', ['class'=>"form-control"]) }}
        </div>

    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::label('bl_receive_date', 'Дата выдачи больничного листа') }}
            {{ Form::date('bl_receive_date', $bl_receive_date ?? null, ['class'=>"form-control"]) }}
        </div>
    </div>
</div>

<div class="row border border-primary p-2">
    <div class="col-sm pr-0">
        <div class="form-group">
            {{ Form::label('take_1', 'Забор №1') }}
            {{ Form::date('take_1', $take_1 ?? null, ['class'=>"form-control"]) }}
        </div>
        <div class="form-group">
            {{ Form::label('take_1_result', 'Результат') }}
            {{ Form::select('take_1_result', ['0' => 'Отрицательный', '1' => 'Положительный'], $take_1_result ?? '0', ['class'=>"form-control"]) }}
        </div>
    </div>
    <div class="col-sm pl-0 border-right border-primary">
        <div class="form-group">
            {{ Form::label('take_1_comment', 'Коммент') }}
            {{ Form::textarea('take_1_comment', $take_1_comment ?? null, ['class'=>"form-control", 'rows'=> '5']) }}
        </div>
    </div>
    <div class="col-sm pr-0">
        <div class="form-group">
            {{ Form::label('take_2', 'Забор №2') }}
            {{ Form::date('take_2', $take_2 ?? null, ['class'=>"form-control"]) }}
        </div>
        <div class="form-group">
            {{ Form::label('take_2_result', 'Результат') }}
            {{ Form::select('take_2_result', ['0' => 'Отрицательный', '1' => 'Положительный'], $take_2_result ?? '0', ['class'=>"form-control"]) }}
        </div>
    </div>
    <div class="col-sm pl-0 border-right border-primary">
        <div class="form-group">
            {{ Form::label('take_2_comment', 'Коммент') }}
            {{ Form::textarea('take_2_comment', $take_2_comment ?? null, ['class'=>"form-control", 'rows'=> '5']) }}
        </div>

    </div>
    <div class="col-sm pr-0">
        <div class="form-group">
            {{ Form::label('take_3', 'Забор №3') }}
            {{ Form::date('take_3', $take_3 ?? null, ['class'=>"form-control"]) }}
        </div>
        <div class="form-group">
            {{ Form::label('take_3_result', 'Результат') }}
            {{ Form::select('take_3_result', ['0' => 'Отрицательный', '1' => 'Положительный'], $take_3_result ?? '0', ['class'=>"form-control"]) }}
        </div>
    </div>
    <div class="col-sm pl-0">
        <div class="form-group">
            {{ Form::label('take_3_comment', 'Коммент') }}
            {{ Form::textarea('take_3_comment', $take_3_comment ?? null, ['class'=>"form-control", 'rows'=> '5']) }}
        </div>
    </div>
</div>
<div class="form-group">
    {{ Form::label('isolation_conditions', 'Условия изоляции') }}
    {{ Form::select('isolation_conditions', config('constants.isolation_conditions'), $isolation_conditions ?? null, ['class'=>"form-control"]) }}
</div>

<div class="form-group">
    {{ Form::label('control_end_date', 'Дата окончания контроля') }}
    {{ Form::date('control_end_date', $control_end_date ?? null, ['class'=>"form-control"]) }}
</div>
<div class="form-group">
    {{ Form::label('control_result', 'Исход контроля') }}
    {{ Form::select('control_result', config('constants.control_result'), $control_result ?? null, ['class'=>"form-control"]) }}
</div>


<div class="form-group">
    {{ Form::submit('Создать') }}
</div>

{{ Form::close() }}
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')
@section('content')
<h2>Все пациенты</h2>
{{ Form::open(array('route' => 'search' , 'method' => 'post')) }}
<div class="row">

    <div class="col-sm col-md-2">
        <a href="{{ route('user.create') }}" type="button" class="btn btn-primary btn-sm mb-1">Добавить +</a>
        <a href="{{ route('stat') }}" type="button" class="btn btn-primary btn-sm mb-1">Статистика +</a>
    </div>

    <div class="col-sm">

        <div class="form-group">
            {{ Form::text('last_name', $search_params['last_name'] ?? null, ['class'=>"form-control", 'placeholder'=>"Поиск по Фамилии"]) }}
        </div>

    </div>
    <div class="col-sm">
        <div class="form-group">
            {{ Form::number('hospital_number', $search_params['hospital_number'] ?? null, ['class'=>"form-control",'placeholder'=>"Номер отделения"]) }}
        </div>
    </div>
    <div class="col-sm ">
        <div class='ml-2'>
            {{ Form::checkbox('users_under_control', null, $search_params['users_under_control'] ?? true,[ 'class'=>'form-check-input', 'style'=>'width:20px; height:20px;' ])}}
            {{ Form::label('hospital_number', ' На контроле' , [ 'class'=>'form-check-label','style'=>'font-size:18px;' ]) }}
        </div>
    </div>
    <div class="col-sm ">
        <div class="form-group">
            {{ Form::submit('Поиск' , ['class'=>'btn btn-primary']) }}
        </div>
    </div>

    <div class="col-sm">
        Всего выбрано записей: {{count($users)}}
    </div>

</div>
{{ Form::close() }}



<div class="col-sm 12 " style="overflow:auto; height:100%; max-height:84vh;">
    <style>
    tr td {
        padding: 0 !important;
        margin: 0 !important;
        white-space: nowrap;
    }
    </style>
    <table class="table table-striped table-bordered" style='padding:0 !important;'>
        @foreach ($users as $user)
        @if ($loop->first)
        <thead style="position: sticky; top: -1%; background:#eee;">
            @foreach ($user->getAttributes() as $key=> $user_prop)
            <th style="position: sticky; top: -1%; background:#eee; white-space: nowrap;">
                {{ config('constants.teble_fields.' . $key)}}
            </th>
            @endforeach
        </thead>
        <tbody>
            @endif
            <tr>
                @foreach ($user->getAttributes() as $key=> $user_prop)
                <td>
                    @if ($loop->first)
                    <div style='display:flex;'>
                        <a href="{{ route('user.show', ['user' => $user_prop])}}" type="button" class="btn btn-primary btn-sm">
                            <svg width="15px" height="15px" aria-hidden="true" focusable="false" data-prefix="fas"
                                data-icon="info" class="svg-inline--fa fa-info fa-w-6" role="img"
                                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 512">
                                <path fill="currentColor"
                                    d="M20 424.229h20V279.771H20c-11.046 0-20-8.954-20-20V212c0-11.046 8.954-20 20-20h112c11.046 0 20 8.954 20 20v212.229h20c11.046 0 20 8.954 20 20V492c0 11.046-8.954 20-20 20H20c-11.046 0-20-8.954-20-20v-47.771c0-11.046 8.954-20 20-20zM96 0C56.235 0 24 32.235 24 72s32.235 72 72 72 72-32.235 72-72S135.764 0 96 0z">
                                </path>
                            </svg></a>
                        <a href="{{ route('user.edit', ['user' => $user_prop])}}" type="button" class="btn btn-primary btn-sm"><svg
                                width="15px" height="15px" aria-hidden="true" focusable="false" data-prefix="fas"
                                data-icon="user-edit" class="svg-inline--fa fa-user-edit fa-w-20" role="img"
                                xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
                                <path fill="currentColor"
                                    d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h274.9c-2.4-6.8-3.4-14-2.6-21.3l6.8-60.9 1.2-11.1 7.9-7.9 77.3-77.3c-24.5-27.7-60-45.5-99.9-45.5zm45.3 145.3l-6.8 61c-1.1 10.2 7.5 18.8 17.6 17.6l60.9-6.8 137.9-137.9-71.7-71.7-137.9 137.8zM633 268.9L595.1 231c-9.3-9.3-24.5-9.3-33.8 0l-37.8 37.8-4.1 4.1 71.8 71.7 41.8-41.8c9.3-9.4 9.3-24.5 0-33.9z">
                                </path>
                            </svg></a>

                        <!--a href="#" type="button" class="btn btn-primary btn-sm">
                    <svg width="15px" height="15px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="microscope" class="svg-inline--fa fa-microscope fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M160 320h12v16c0 8.84 7.16 16 16 16h40c8.84 0 16-7.16 16-16v-16h12c17.67 0 32-14.33 32-32V64c0-17.67-14.33-32-32-32V16c0-8.84-7.16-16-16-16h-64c-8.84 0-16 7.16-16 16v16c-17.67 0-32 14.33-32 32v224c0 17.67 14.33 32 32 32zm304 128h-1.29C493.24 413.99 512 369.2 512 320c0-105.88-86.12-192-192-192v64c70.58 0 128 57.42 128 128s-57.42 128-128 128H48c-26.51 0-48 21.49-48 48 0 8.84 7.16 16 16 16h480c8.84 0 16-7.16 16-16 0-26.51-21.49-48-48-48zm-360-32h208c4.42 0 8-3.58 8-8v-16c0-4.42-3.58-8-8-8H104c-4.42 0-8 3.58-8 8v16c0 4.42 3.58 8 8 8z"></path></svg></a>

                <a href="#" type="button" class="btn btn-primary btn-sm">
                <svg width="15px" height="15px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="thermometer" class="svg-inline--fa fa-thermometer fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M476.8 20.4c-37.5-30.7-95.5-26.3-131.9 10.2l-45.7 46 50.5 50.5c3.1 3.1 3.1 8.2 0 11.3l-11.3 11.3c-3.1 3.1-8.2 3.1-11.3 0l-50.4-50.5-45.1 45.4 50.3 50.4c3.1 3.1 3.1 8.2 0 11.3l-11.3 11.3c-3.1 3.1-8.2 3.1-11.3 0L209 167.4l-45.1 45.4L214 263c3.1 3.1 3.1 8.2 0 11.3l-11.3 11.3c-3.1 3.1-8.2 3.1-11.3 0l-50.1-50.2L96 281.1V382L7 471c-9.4 9.4-9.4 24.6 0 33.9 9.4 9.4 24.6 9.4 33.9 0l89-89h99.9L484 162.6c34.9-34.9 42.2-101.5-7.2-142.2z"></path></svg></a -->
                    </div>

                    @else
                    {{ $user_prop }}
                    @endif
                </td>
                @endforeach
            </tr>
            @endforeach
    </table>
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.app')
@section('content')
<h1>{{$last_name}} {{$name}} {{$second_name}} {{$birth_day ? "(" . $birth_day . ")" : ""}}</h1>
<div class="row">
    <div class="col-sm">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Контакты</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{$phone_number}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">{{$email}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">{{$current_address}}</h6>
                <a href="{{ route('user.edit', ['user' => $id])}}" class="card-link">Изменить</a>
            </div>
        </div>
    </div>
    <div class="col-sm">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Доп информация</h5>
                <h6 class="card-subtitle mb-2 text-muted">Место работы: {{$job}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Нужен БЛ: {{$is_need_bl === 1? "Да" : "Нет"}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Дата выдачи БЛ: {{$bl_receive_date}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Количество детей: {{$child_qty}}</h6>
                <a href="{{ route('user.edit', ['user' => $id])}}" class="card-link">Изменить</a>
            </div>
        </div>
    </div>
    <div class="col-sm">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Источник</h5>

                <h6 class="card-subtitle mb-2 text-muted">Номер отделения: {{$hospital_number}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Дата прибытия: {{$arrival_date}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Страна прибытия / контакт: {{$arrival_country}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Дата окончания карантина: {{$quarantine_end_date}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Условия изоляции: {{$isolation_conditions}}</h6>

                <h6 class="card-subtitle mb-2 text-muted">Дата окончания контроля: {{$control_end_date}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Исход: {{$control_result}}</h6>
                <a href="{{ route('user.edit', ['user' => $id])}}" class="card-link">Изменить</a>
            </div>
        </div>
    </div>


</div>
<h5 class="card-title">Анализы</h5>
<div class="row">

    <div class="col-sm">
        <div class="card">
            <div class="card-body">

                <h6 class="card-subtitle mb-2 text-muted">Дата 1: {{$take_1}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Коммент 1: {{$take_1_comment}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Результат:
                    {{$take_1_result === 1? "Положительный" : "Отрицательный"}}</h6>
                <a href="{{ route('user.edit', ['user' => $id])}}" class="card-link">Изменить</a>
            </div>
        </div>
    </div>
    <div class="col-sm">
        <div class="card">
            <div class="card-body">


                <h6 class="card-subtitle mb-2 text-muted">Дата 2: {{$take_2}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Коммент 2: {{$take_2_comment}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Результат:
                    {{$take_2_result === 1? "Положительный" : "Отрицательный"}}</h6>
                <a href="{{ route('user.edit', ['user' => $id])}}" class="card-link">Изменить</a>
            </div>
        </div>
    </div>
    <div class="col-sm">
        <div class="card">
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted">Дата 3: {{$take_3}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Коммент 3: {{$take_3_comment}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">Результат:
                    {{$take_3_result === 1? "Положительный" : "Отрицательный"}}</h6>
                <a href="{{ route('user.edit', ['user' => $id])}}" class="card-link">Изменить</a>
            </div>
        </div>
    </div>
</div>
<div class="row mt-3">
    <div class="col-sm">
        <div class="card border border-primary">
            <div class="card-body border-bottom border-secondary">
                {{ Form::open(array('route' => 'tmc.store')) }}
                {{ Form::hidden('user_id', $id) }}
                <div class="row">
                    <div class="col-sm col-md-3">
                        <div class="form-group">
                            {{ Form::label('diagnosis_code', 'Диагноз COVID-19') }}
                            {{ Form::select('diagnosis_code', config('constants.covid_diagnoses'), $diagnosis_code ?? null, ['class'=>"form-control"]) }}
                        </div>
                    </div>
                    <div class="col-sm col-md-4">
                        <div class="form-group">
                            {{ Form::label('ext_diagnosis_code', 'Сопутствующий диагноз') }}
                            {{ Form::text('ext_diagnosis_code', null, ['class'=>"form-control", 'placeholder'=>""]) }}
                        </div>
                    </div>
                    <div class="col-sm col-md-2">
                        <div class="form-group">
                            {{ Form::label('tmc_date', 'Дата ТМС') }}
                            {{ Form::date('tmc_date', null, ['class'=>"form-control" ]) }}
                        </div>
                    </div>
                    <div class="col-sm col-md-3">
                        <div class="form-group">
                            {{ Form::label('consultant_name', 'Консультант (обязательное поле)') }}
                            {{ Form::text('consultant_name', null, ['class'=>"form-control", 'placeholder'=>"ФИО и/или название учреждения"]) }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::submit('Добавить запись', ['class'=>'btn btn-primary']) }}
                </div>
                {{ Form::close() }}
            </div>
            <table class="table">
                <tr>
                    <td>Дата время внесения</td>
                    <td>Дата ТМС</td>
                    <td>Основной диагноз</td>
                    <td>Сопутствующий диагноз</td>
                    <td>Консультант</td>
                </tr>
                @foreach ($telemedicines->reverse() as $tmc)
                <tr>
                    <td>{{$tmc->created_at}}</td>
                    <td>{{$tmc->tmc_date}}</td>
                    <td>{{$tmc->diagnosis_code}}</td>
                    <td>{{$tmc->ext_diagnosis_code}}</td>
                    <td>{{$tmc->consultant_name}}</td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>
<div class="row mt-3">
    <div class="col-sm">
        <div class="card border border-primary">
            <div class="card-body border-bottom border-secondary">
                <h3 class="card-subtitle mb-2 text-muted">Таблица состояний</h3>

                {{ Form::open(array('route' => 'status.store')) }}
                <div class="row">
                    <div class="col-sm col-md-4">

                        {{ Form::hidden('user_id', $id) }}

                        <div class="form-group">
                            {{ Form::label('date', 'Дата') }}
                            {{ Form::date('date', \Carbon\Carbon::now(), ['class'=>"form-control", 'min'=> \Carbon\Carbon::now()->add(-1, 'day') ]) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('temperature', 'Температура') }}
                            {{ Form::number('temperature', null, ['class'=>"form-control", 'min'=>"35" ,'max'=>"42", 'step'=>"0.1"]) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('cough_pain_throat', 'Есть кашель или боль в горле') }}
                            {{ Form::select('cough_pain_throat', [''=>'нет данных','0' => 'Нет', '1' => 'Да'], null, ['class'=>"form-control"]) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('short_wind', 'Затруднено дыхание') }}
                            {{ Form::select('short_wind', [''=>'нет данных', '0' => 'Нет', '1' => 'Да'], null, ['class'=>"form-control"]) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('need_consult', 'Есть иные симптомы или требуется консультация врача') }}
                            {{ Form::select('need_consult', [''=>'нет данных','0' => 'Нет', '1' => 'Да'], null, ['class'=>"form-control"]) }}
                        </div>
                    </div>
                    <div class="col-sm col-md-8">
                        <div class="form-group">
                            {{  Form::textarea('comment', null, ['style'=>'width:100%', 'placeholder'=>'Иное / Комментарий'] )  }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::submit('Добавить запись') }}
                </div>
                {{ Form::close() }}

            </div>
            <table class="table">

                <tr>
                    <td>Дата время внесения</td>
                    <td>Статус за дату</td>
                    <td>Температура</td>
                    <td>Кашель или боль в горле</td>
                    <td>Затруднено дыхание</td>
                    <td>Иные симптомы</td>
                    <td>Комментарий</td>
                </tr>
                @foreach ($statuses->reverse() as $status)
                <tr>
                    <td>{{$status->created_at}}</td>
                    <td>{{$status->date}}</td>
                    <td>{{$status->temperature}}</td>
                    <td>{{$status->cough_pain_throat}}</td>
                    <td>{{$status->short_wind}}</td>
                    <td>{{$status->need_consult}}</td>
                    <td>{{$status->comment}}</td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>

<script>

</script>

@endsection